import { SEMANTIC_COLORS, colors, type ColorToken, type ThemeName } from './colors';
import { motion, radius, shadow, type } from './scale';
import { stateStyles } from './states';

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

function themeVars(theme: ThemeName): string[] {
  const lines = SEMANTIC_COLORS.map((k) => `  --color-${kebab(k)}: ${colors[theme][k]};`);
  for (const [state, style] of Object.entries(stateStyles)) {
    const name = state.toLowerCase().replace(/_/g, '-');
    lines.push(`  --state-${name}-bg: ${style[theme].bg};`, `  --state-${name}-text: ${style[theme].text};`);
  }
  return lines;
}

/** `:root` (light) and `.dark` variable blocks. `color-scheme` follows the theme for native form controls. */
export function generateCssVariables(): string {
  const shared = [
    ...Object.entries(radius).map(([k, v]) => `  --radius-${k}: ${v}px;`),
    ...Object.entries(type).map(([k, t]) => `  --text-${kebab(k)}: ${t.size}px;`),
    `  --shadow-popover: ${shadow.popover};`,
    `  --motion-fast: ${motion.fast}ms;`,
    `  --motion-base: ${motion.base}ms;`,
  ];
  return [
    '/* Generated by @dispatch/ui-tokens (scripts/write-css.js). Do not edit. */',
    ':root {',
    '  color-scheme: light;',
    ...themeVars('light'),
    ...shared,
    '}',
    '.dark {',
    '  color-scheme: dark;',
    ...themeVars('dark'),
    '}',
    '',
  ].join('\n');
}

const UTILITIES: Record<string, ColorToken> = {
  bg: 'bg',
  surface: 'surface',
  'surface-muted': 'surfaceMuted',
  line: 'border',
  'line-strong': 'borderStrong',
  ink: 'text',
  muted: 'textMuted',
  subtle: 'textSubtle',
  primary: 'primary',
  'primary-hover': 'primaryHover',
  'primary-soft': 'primarySoft',
  'on-primary': 'onPrimary',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
  focus: 'focus',
};

/** Tailwind v4 `@theme` block exposing the variables as utilities (bg-surface, text-muted, border-line, ...). */
export function tailwindThemeCss(): string {
  return [
    '@custom-variant dark (&:where(.dark, .dark *));',
    '',
    '@theme inline {',
    ...Object.entries(UTILITIES).map(([util, token]) => `  --color-${util}: var(--color-${kebab(token)});`),
    '}',
    '',
  ].join('\n');
}

/** Tailwind (v3-style) preset with the same mapping, for consumers that use a JS config. */
export const tailwindPreset = {
  darkMode: 'class' as const,
  theme: {
    extend: {
      colors: Object.fromEntries(
        SEMANTIC_COLORS.map((k) => [kebab(k), `var(--color-${kebab(k)})`]),
      ) as Record<string, string>,
      borderRadius: { sm: '8px', md: '12px', lg: '16px' },
      boxShadow: { popover: shadow.popover },
      transitionDuration: { fast: `${motion.fast}ms`, base: `${motion.base}ms` },
    },
  },
};
